import { PGlite } from '@electric-sql/pglite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { setQueryExecutor } from '../scripts/analytics/db';
import { formatConnection } from '../scripts/analytics/format';
import { resolvePeriod } from '../scripts/analytics/periods';
import { getConnection } from '../scripts/analytics/queries';
import {
  CONNECTION_COVERAGE_NOTE,
  buildCommandEnvelope,
  type ResolvedPeriod
} from '../scripts/analytics/types';

/**
 * 032 — `npm run analytics -- connection` runs its exact SQL against an
 * in-process Postgres. Two people on two web builds: one build emits the
 * link lifecycle, the other predates it and must be named as uncovered.
 */

let db: PGlite;
let ALL: ResolvedPeriod;

const ALICE = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const BOB = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const FLOW_A = '10000000-0000-4000-8000-000000000001';
const FLOW_B = '10000000-0000-4000-8000-000000000002';
const NEW_BUILD = 'web-0.32.0';
const OLD_BUILD = 'web-0.31.4';

beforeAll(async () => {
  db = await PGlite.create();
  await db.exec(`
    create table public.analytics_events (
      id bigint generated by default as identity primary key,
      user_id uuid,
      event_name text not null,
      session_id uuid,
      tool text,
      properties jsonb not null default '{}'::jsonb,
      occurred_at timestamptz not null default now(),
      flow_id uuid,
      web_build_id text,
      outcome text,
      created_at timestamptz not null default now()
    );

    insert into public.analytics_events (user_id, event_name, flow_id, web_build_id, outcome, properties) values
      ('${ALICE}','link_check_started','${FLOW_A}','${NEW_BUILD}',null,'{"link_trigger":"boot","link_origin":"hosted","browser_family":"chrome"}'),
      ('${ALICE}','link_check_completed','${FLOW_A}','${NEW_BUILD}','failure','{"outcome":"failure","link_reason":"not_running","link_stage":"probe","duration_ms":812}'),
      ('${ALICE}','link_lost','${FLOW_A}','${NEW_BUILD}',null,'{"link_transport":"stream","link_reason":"unknown"}'),
      ('${ALICE}','link_recovered','${FLOW_A}','${NEW_BUILD}',null,'{"duration_ms":2000,"recovery_mode":"auto","instance_changed":false,"token_changed":false}'),
      ('${ALICE}','link_lost','${FLOW_A}','${NEW_BUILD}',null,'{"link_transport":"watchdog"}'),
      ('${ALICE}','reconnect_clicked','${FLOW_A}','${NEW_BUILD}',null,'{"surface":"header_badge"}'),
      ('${ALICE}','link_recovered','${FLOW_A}','${NEW_BUILD}',null,'{"duration_ms":10000,"recovery_mode":"manual","instance_changed":true,"token_changed":false}'),
      ('${ALICE}','link_inconsistency','${FLOW_A}','${NEW_BUILD}',null,'{"link_transport":"request","error_code":"unauthorized","link_stream_open":true}'),
      ('${BOB}','link_check_started','${FLOW_B}','${NEW_BUILD}',null,'{"link_trigger":"boot","link_origin":"hosted","browser_family":"safari"}'),
      ('${BOB}','blocked_by_browser_detected',null,'${NEW_BUILD}',null,'{"browser_family":"safari","link_origin":"hosted"}'),
      ('${BOB}','link_check_completed','${FLOW_B}','${NEW_BUILD}',null,'{"outcome":"blocked","link_reason":"blocked_by_browser","link_stage":"probe","duration_ms":30}'),
      ('${BOB}','link_check_started','${FLOW_B}','${NEW_BUILD}',null,'{"link_trigger":"manual","link_origin":"local_copy","browser_family":"safari"}'),
      ('${BOB}','link_lost','${FLOW_B}','${NEW_BUILD}',null,'{"link_transport":"stream"}'),
      ('${BOB}','link_recovered','${FLOW_B}','${NEW_BUILD}',null,'{"recovery_mode":"local_copy","instance_changed":false,"token_changed":true}'),
      ('${BOB}','link_recovered','${FLOW_B}','${NEW_BUILD}',null,'{"duration_ms":4000,"recovery_mode":"local_copy","instance_changed":false,"token_changed":false}'),
      ('${BOB}','home_viewed',null,'${OLD_BUILD}',null,'{}'),
      ('${BOB}','agent_disconnected',null,'${OLD_BUILD}',null,'{}'),
      ('${ALICE}','home_viewed',null,null,null,'{}');
  `);

  let chain: Promise<unknown> = Promise.resolve();
  setQueryExecutor((sql, params) => {
    const run = chain.then(async () => {
      const result = await db.query(sql, params as unknown[]);
      return (result.rows as Record<string, unknown>[]).map(row => {
        const out: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(row)) {
          out[key] =
            typeof value === 'string' && /^-?\d+(\.\d+)?$/.test(value) ? Number(value) : value;
        }
        return out;
      });
    });
    chain = run.catch(() => undefined);
    return run;
  });

  ALL = resolvePeriod('all', undefined);
}, 30_000);

afterAll(async () => {
  setQueryExecutor(null);
  await db.close();
});

describe('analytics connection command', () => {
  it('counts losses, recoveries and the time a break lasted', async () => {
    const data = await getConnection(ALL);
    expect(data.users_with_loss).toBe(2);
    expect(data.losses).toBe(3);
    expect(data.recoveries).toBe(4);
    // Three recoveries carry a duration: 2000, 4000, 10000.
    expect(data.recovery_ms).toEqual({ p50: 4000, p95: 9400, samples: 3 });
    expect(data.recovery_mode).toEqual({ auto: 1, manual: 1, local_copy: 2 });
    expect(data.inconsistencies).toEqual({ events: 1, users: 1 });
  });

  it('groups failed checks by reason, blocking by browser, and events by origin', async () => {
    const data = await getConnection(ALL);
    expect(data.failed_checks_by_reason).toEqual([
      { reason: 'blocked_by_browser', events: 1, users: 1 },
      { reason: 'not_running', events: 1, users: 1 }
    ]);
    expect(data.blocked_by_browser).toEqual([{ browser_family: 'safari', users: 1 }]);
    expect(data.origins).toEqual([
      { link_origin: 'hosted', users: 2, events: 3 },
      { link_origin: 'local_copy', users: 1, events: 1 }
    ]);
  });

  it('names the web builds that emit no link event as uncovered, not healthy', async () => {
    const data = await getConnection(ALL);
    expect(data.coverage).toEqual({
      web_builds_with_link_events: 1,
      web_builds_without: [OLD_BUILD],
      note: CONNECTION_COVERAGE_NOTE
    });
    expect(data.coverage.note).toMatch(/uncovered/);
  });

  it('returns an empty shape, not an error, for a period with no events', async () => {
    const empty: ResolvedPeriod = {
      token: 'none',
      start: '2000-01-01T00:00:00.000Z',
      end: '2000-01-02T00:00:00.000Z',
      label: 'an empty day'
    };
    const data = await getConnection(empty);
    expect(data).toEqual({
      users_with_loss: 0,
      losses: 0,
      recoveries: 0,
      recovery_ms: { p50: null, p95: null, samples: 0 },
      recovery_mode: { auto: 0, manual: 0, local_copy: 0 },
      failed_checks_by_reason: [],
      blocked_by_browser: [],
      origins: [],
      inconsistencies: { events: 0, users: 0 },
      coverage: {
        web_builds_with_link_events: 0,
        web_builds_without: [],
        note: CONNECTION_COVERAGE_NOTE
      }
    });
    const human = formatConnection(data, empty);
    expect(human).toContain('—');
  });

  it('wraps the stable envelope and a human table without a person, a token or an id', async () => {
    const data = await getConnection(ALL);
    const envelope = buildCommandEnvelope('connection', ALL, data, '2026-10-10T00:00:00.000Z');
    expect(envelope).toMatchObject({
      ok: true,
      command: 'connection',
      generated_at: '2026-10-10T00:00:00.000Z',
      data
    });
    const human = formatConnection(data, ALL);
    expect(human).toContain('Connection');
    expect(human).toContain('4.0s / 9.4s');
    expect(human).toContain('blocked_by_browser');
    expect(human).toContain(OLD_BUILD);
    expect(human).toContain(CONNECTION_COVERAGE_NOTE);
    // `period.token` is the window's name, so the data and the table are what
    // must stay free of a person, a secret or an identifier.
    const text = JSON.stringify(data) + human;
    expect(text).not.toMatch(
      /@|token|bearer|[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-8[0-9a-f]{3}-[0-9a-f]{12}/i
    );
  });
});
