import { PGlite } from '@electric-sql/pglite';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { setQueryExecutor } from '../scripts/analytics/db';
import { resolvePeriod } from '../scripts/analytics/periods';
import {
  getCompressor,
  getEvents,
  getFunnel,
  getOverview,
  getTools,
  getTopUsers,
  getUserDetail,
  getUsers
} from '../scripts/analytics/queries';
import type { ResolvedPeriod } from '../scripts/analytics/types';

// Runs the CLI's exact SQL against an in-process Postgres (PGlite, no Docker).
// This verifies both that the read-only guard accepts every query and that the
// SQL is valid Postgres that returns the expected aggregates.

let db: PGlite;
// Resolved after the fixture is inserted so the window's end is later than the
// events' created_at (all seeded with now()); otherwise the range excludes them.
let ALL: ResolvedPeriod;

const ALICE = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const BOB = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const CAROL = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const DAVE = 'dddddddd-dddd-4ddd-8ddd-dddddddddddd';

beforeAll(async () => {
  db = await PGlite.create();
  await db.exec(`
    create table public.analytics_users (
      id uuid primary key,
      email text,
      email_normalized text,
      display_name text,
      language text,
      plan text,
      account_status text,
      marketing_consent boolean,
      registered_at timestamptz,
      last_seen_at timestamptz,
      last_login_at timestamptz
    );
    create table public.analytics_events (
      id bigint generated by default as identity primary key,
      user_id uuid,
      event_name text not null,
      session_id uuid,
      tool text,
      properties jsonb not null default '{}'::jsonb,
      app_version text,
      agent_version text,
      locale text,
      platform text,
      created_at timestamptz not null default now()
    );

    insert into public.analytics_users values
      ('${ALICE}','alice@example.com','alice@example.com','Alice','uk','free','active',true, now() - interval '2 days', now() - interval '1 hour', now() - interval '1 hour'),
      ('${BOB}','Bob@Example.com','bob@example.com','Bob','en','pro','active',false, now() - interval '10 days', now() - interval '2 days', now() - interval '2 days'),
      ('${CAROL}','carol@example.com','carol@example.com','Carol','uk','free','active',false, now() - interval '40 days', now() - interval '3 hours', null),
      ('${DAVE}','dave@example.com','dave@example.com','Dave','en','free','deleted',false, now() - interval '5 days', now() - interval '5 days', null);

    insert into public.analytics_events (user_id, event_name, session_id, tool, properties, locale, platform, app_version, agent_version) values
      ('${ALICE}','tool_opened','11111111-1111-4111-8111-111111111111','compressor','{"tool_identifier":"compressor"}','uk','macos','0.4.0','0.4.0'),
      ('${ALICE}','videos_added','11111111-1111-4111-8111-111111111111','compressor','{"video_count":3}','uk','macos','0.4.0','0.4.0'),
      ('${ALICE}','compression_batch_started','11111111-1111-4111-8111-111111111111','compressor','{"mode":"optimal","video_count":3}','uk','macos','0.4.0','0.4.0'),
      ('${ALICE}','compression_started','11111111-1111-4111-8111-111111111111','compressor','{}','uk','macos','0.4.0','0.4.0'),
      ('${ALICE}','compression_started','11111111-1111-4111-8111-111111111111','compressor','{}','uk','macos','0.4.0','0.4.0'),
      ('${ALICE}','compression_completed','11111111-1111-4111-8111-111111111111','compressor','{"mode":"optimal","total_input_bytes":1000,"total_output_bytes":400,"saving_percent":60,"processing_duration_ms":5000}','uk','macos','0.4.0','0.4.0'),
      ('${ALICE}','compression_completed','11111111-1111-4111-8111-111111111111','compressor','{"mode":"optimal","total_input_bytes":2000,"total_output_bytes":1000,"saving_percent":50,"processing_duration_ms":7000}','uk','macos','0.4.0','0.4.0'),
      ('${BOB}','tool_opened','22222222-2222-4222-8222-222222222222','compressor','{"tool_identifier":"compressor"}','en','windows','0.4.0','0.4.0'),
      ('${BOB}','compression_started','22222222-2222-4222-8222-222222222222','compressor','{}','en','windows','0.4.0','0.4.0'),
      ('${BOB}','compression_failed','22222222-2222-4222-8222-222222222222','compressor','{"error_category":"network"}','en','windows','0.4.0','0.4.0'),
      ('${CAROL}','home_viewed','33333333-3333-4333-8333-333333333333',null,'{}','uk','macos','0.4.0',null);
  `);

  // PGlite has a single connection and does not tolerate overlapping queries;
  // a real pg Pool (max 3) does. Serialize here so Promise.all call sites in the
  // CLI behave against this harness exactly as they do in production.
  let chain: Promise<unknown> = Promise.resolve();
  setQueryExecutor((sql, params) => {
    const run = chain.then(async () => {
      const result = await db.query(sql, params as unknown[]);
      // Mirror production's bigint/numeric -> number coercion (see db.ts type parsers).
      return (result.rows as Record<string, unknown>[]).map(row => {
        const out: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(row)) {
          out[key] =
            typeof value === 'string' && /^-?\d+(\.\d+)?$/.test(value) ? Number(value) : value;
        }
        return out;
      });
    });
    chain = run.catch(() => undefined);
    return run;
  });

  ALL = resolvePeriod('all', undefined);
});

afterAll(async () => {
  setQueryExecutor(null);
  await db.close();
});

describe('getOverview', () => {
  it('aggregates users, sessions and event counts', async () => {
    const data = await getOverview(ALL);
    expect(data.total_users).toBe(3); // Dave is deleted
    expect(data.sessions).toBe(3);
    expect(data.tool_opens).toBe(2);
    expect(data.compression_batches).toBe(1);
    expect(data.videos_added).toBe(3);
    expect(data.videos_compressed).toBe(2);
    expect(data.compressions_failed).toBe(1);
    expect(data.top_locales[0]).toEqual({ name: 'uk', count: expect.any(Number) });
    expect(data.top_platforms.map(p => p.name)).toContain('macos');
  });
});

describe('getCompressor', () => {
  it('computes funnel, sizes and ratios', async () => {
    const data = await getCompressor(ALL);
    expect(data.unique_users).toBe(2);
    expect(data.tool_opens).toBe(2);
    expect(data.videos_added).toBe(3);
    expect(data.compression_started).toBe(3);
    expect(data.compression_completed).toBe(2);
    expect(data.compression_failed).toBe(1);
    expect(data.started_without_completion).toBe(1);
    expect(data.batch_count).toBe(1);
    expect(data.average_batch_size).toBe(2);
    expect(data.total_input_bytes).toBe(3000);
    expect(data.total_output_bytes).toBe(1400);
    expect(data.saved_bytes).toBe(1600);
    expect(data.average_saving_percent).toBe(55);
    expect(data.success_rate).toBeCloseTo(2 / 3, 4);
    expect(data.average_duration_ms).toBe(6000);
  });
});

describe('getUsers / getTopUsers', () => {
  it('returns totals and rankings', async () => {
    const users = await getUsers(ALL);
    expect(users.total_users).toBe(3);
    expect(users.active_users).toBe(3); // Alice, Bob, Carol all have last_seen
    expect(users.last_active[0].email).toBe('alice@example.com');

    const byCompressions = await getTopUsers(ALL, 'compressions');
    expect(byCompressions.users[0].email).toBe('alice@example.com');
    expect(byCompressions.users[0].compressions).toBe(2);

    const byActivity = await getTopUsers(ALL, 'activity');
    expect(byActivity.users[0].email).toBe('alice@example.com');
    expect(byActivity.users[0].event_count).toBe(7);
  });
});

describe('getUserDetail', () => {
  it('resolves a user case-insensitively with full stats', async () => {
    const detail = await getUserDetail('bob@example.com');
    expect(detail).not.toBeNull();
    expect(detail?.display_name).toBe('Bob');
    expect(detail?.total_events).toBe(3);
    expect(detail?.compressions_completed).toBe(0);
    expect(detail?.recent_events.length).toBe(3);
    expect(detail?.tool_usage[0]).toEqual({ name: 'compressor', count: 3 });
  });

  it('returns null for an unknown email', async () => {
    expect(await getUserDetail('nobody@example.com')).toBeNull();
  });
});

describe('getTools / getEvents / getFunnel', () => {
  it('breaks down tools and events', async () => {
    const tools = await getTools(ALL);
    const compressor = tools.find(t => t.tool === 'compressor');
    expect(compressor?.opens).toBe(2);
    expect(compressor?.starts).toBe(3);
    expect(compressor?.completions).toBe(2);

    const events = await getEvents(ALL);
    const completed = events.find(e => e.event_name === 'compression_completed');
    expect(completed?.count).toBe(2);
    expect(completed?.unique_users).toBe(1);
  });

  it('computes the compressor funnel by unique users', async () => {
    const funnel = await getFunnel(ALL);
    const byStage = Object.fromEntries(funnel.map(s => [s.stage, s.users]));
    expect(byStage.tool_opened).toBe(2);
    expect(byStage.videos_added).toBe(1);
    expect(byStage.compression_started).toBe(2);
    expect(byStage.compression_completed).toBe(1);
    expect(funnel[3].conversion_from_start).toBe(0.5);
  });
});
