import { describe, expect, it } from 'vitest';
import { buildFfmpegArgs } from '../apps/agent/src/ffmpeg/presets.js';
describe('preset argument arrays', () => {
  it('defines Quality without resizing', () => { const a=buildFfmpegArgs('in.mov','out.mp4','quality'); expect(a).toContain('24'); expect(a).toContain('copy'); expect(a).not.toContain('-vf'); });
  it('defines Balanced with 720 and non-increasing 24 FPS', () => { const a=buildFfmpegArgs('in.mov','out.mp4','balanced'); expect(a).toContain('26'); expect(a.join(' ')).toContain('min(720'); expect(a.join(' ')).toContain('min(24,source_fps)'); expect(a).toContain('96k'); });
  it('defines Ultra Small with 550, 20 FPS and mono audio', () => { const a=buildFfmpegArgs('in.mov','out.mp4','ultra-small'); expect(a).toContain('30'); expect(a).toContain('veryslow'); expect(a.join(' ')).toContain('min(550'); expect(a.join(' ')).toContain('min(20,source_fps)'); expect(a).toContain('48k'); expect(a).toContain('1'); });
  it('passes paths as intact arguments and never enables overwrite', () => { const a=buildFfmpegArgs('/tmp/Моє відео.mov','/tmp/out file.mp4','balanced'); expect(a).toContain('/tmp/Моє відео.mov'); expect(a).toContain('/tmp/out file.mp4'); expect(a).toContain('-n'); });
  it('caps Quality frame rate with the chosen rate', () => { const a=buildFfmpegArgs('in.mov','out.mp4','quality',{frameRate:72}); expect(a.join(' ')).toContain("fps='min(72,source_fps)'"); expect(a.join(' ')).not.toContain('scale='); });
  it('never lets a higher frame rate raise a preset above its own cap', () => { expect(buildFfmpegArgs('in.mov','out.mp4','balanced',{frameRate:120}).join(' ')).toContain('min(24,source_fps)'); expect(buildFfmpegArgs('in.mov','out.mp4','ultra-small',{frameRate:120}).join(' ')).toContain('min(20,source_fps)'); });
  it('applies the Quality CRF override', () => { const a=buildFfmpegArgs('in.mov','out.mp4','quality',{crf:18}); const i=a.indexOf('-crf'); expect(a[i+1]).toBe('18'); expect(a).not.toContain('-b:v'); });
  it('uses target bitrate instead of CRF when set on Quality', () => { const a=buildFfmpegArgs('in.mov','out.mp4','quality',{crf:18,videoBitrateKbps:4000}); expect(a).not.toContain('-crf'); const i=a.indexOf('-b:v'); expect(a[i+1]).toBe('4000k'); expect(a.join(' ')).toContain('-maxrate 4000k'); });
  it('downscales Quality only when keep-resolution is off', () => { expect(buildFfmpegArgs('in.mov','out.mp4','quality',{keepResolution:true}).join(' ')).not.toContain('scale='); expect(buildFfmpegArgs('in.mov','out.mp4','quality',{keepResolution:false}).join(' ')).toContain('min(1920'); });
  it('uses a custom longest side when keep-resolution is off', () => { expect(buildFfmpegArgs('in.mov','out.mp4','quality',{keepResolution:false,resolutionLimit:1280}).join(' ')).toContain('min(1280'); expect(buildFfmpegArgs('in.mov','out.mp4','quality',{keepResolution:true,resolutionLimit:1280}).join(' ')).not.toContain('scale='); });
  it('ignores the manual controls on Balanced and Ultra Small', () => { const a=buildFfmpegArgs('in.mov','out.mp4','balanced',{crf:14,videoBitrateKbps:9000,keepResolution:true}); const i=a.indexOf('-crf'); expect(a[i+1]).toBe('26'); expect(a).not.toContain('-b:v'); expect(a.join(' ')).toContain('min(720'); });
});
