import { afterEach, describe, expect, it } from 'vitest'; import { copyFile, mkdtemp, rm, writeFile } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import { JobQueue } from '../apps/agent/src/queue/queue.js';
import { spawn } from 'node:child_process';
let dir='';afterEach(async()=>{if(dir)await rm(dir,{recursive:true,force:true})});
describe('queue behavior',()=>{it('warns for duplicates and permits an explicit retry',async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'queue-'));const file=path.join(dir,'clip.mov');await writeFile(file,'x');const q=new JobQueue({ffmpeg:false,ffprobe:false},()=>{});expect(await q.add([file])).toEqual([]);const warnings=await q.add([file]);expect(warnings[0].reason).toBe('duplicate');await q.add([file],true);expect(q.state().jobs).toHaveLength(2)});it('requeues failed and interrupted jobs',()=>{const base={id:'1',inputPath:'/missing',outputPath:'/out',fileName:'x',durationSeconds:null,originalSize:1,finalSize:null,progress:null,error:'bad',preset:'balanced' as const};const q=new JobQueue({ffmpeg:false,ffprobe:false},()=>{},[{...base,status:'failed'}],{preset:'balanced',outputMode:'next-to-originals',outputFolder:null});expect(q.retry('1')).toBe(true);expect(q.state().jobs[0].status).toBe('queued')});it('continues after one file fails and can retry it',async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'queue-flow-'));const bad=path.join(dir,'bad.mov'),good=path.join(dir,'good.mov');await writeFile(bad,'not video');expect(await run(['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc2=size=160x90:rate=10','-t','0.3','-c:v','libx264','-an',good])).toBe(0);const q=new JobQueue({ffmpeg:true,ffprobe:true},()=>{});await q.add([bad,good]);await q.start();await until(()=>q.state().jobs.every(j=>['failed','completed'].includes(j.status)));expect(q.state().jobs.map(j=>j.status)).toEqual(['failed','completed']);expect(q.retry(q.state().jobs[0].id)).toBe(true);expect(q.state().jobs[0].status).toBe('queued')},15000);it('keeps a cancelled job out of completed',async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'queue-cancel-'));const input=path.join(dir,'long.mov');expect(await run(['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc2=size=1280x720:rate=30','-t','4','-c:v','libx264','-preset','ultrafast','-an',input])).toBe(0);const q=new JobQueue({ffmpeg:true,ffprobe:true},()=>{},[],{preset:'ultra-small',outputMode:'next-to-originals',outputFolder:null});await q.add([input]);await q.start();await until(()=>q.state().jobs[0].status==='processing');expect(await q.cancel(q.state().jobs[0].id)).toBe(true);await until(()=>q.state().jobs[0].status==='cancelled'&&!q.state().running);expect(q.state().jobs[0].finalSize).toBeNull()},15000)});
describe('priority estimate handoff',()=>{it('pauses compression, queues requests, supports cancellation, and resumes the same job',async()=>{
  dir=await mkdtemp(path.join(os.tmpdir(),'queue-estimate-priority-'));const first=path.join(dir,'first.mov'),second=path.join(dir,'second.mov'),third=path.join(dir,'third.mov');
  expect(await run(['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc2=size=1280x720:rate=30','-t','4','-c:v','libx264','-preset','ultrafast','-an',first])).toBe(0);await copyFile(first,second);await copyFile(first,third);
  const q=new JobQueue({ffmpeg:true,ffprobe:true},()=>{},[],{preset:'ultra-small',outputMode:'next-to-originals',outputFolder:null});await q.add([first,second,third]);const secondId=q.state().jobs[1].id,thirdId=q.state().jobs[2].id;
  let release=()=>{};const gate=new Promise<void>(resolve=>{release=resolve});const handoffs:{active:boolean;statuses:string[];priorityOrder:number|null|undefined}[]=[];
  q.attachEstimator({schedule:()=>{},invalidateForPreset:()=>{},resume:()=>{},runPrioritized:async()=>{const snapshot=q.state();handoffs.push({active:q.compressionActive(),statuses:snapshot.jobs.map(candidate=>candidate.status),priorityOrder:snapshot.jobs[1].estimatePriorityOrder});q.updateEstimate(secondId,{estimateStatus:'estimated',estimatedOutputBytes:500,estimatePriorityOrder:null},'estimate:completed');await gate;return true}});
  await q.start();await until(()=>q.state().jobs[0].status==='processing');expect(q.prioritizeEstimate(secondId)).toBe(true);await until(()=>handoffs.length===1);
  expect(handoffs[0]).toEqual({active:false,statuses:['processing','queued','queued'],priorityOrder:1});expect(q.state().running).toBe(true);
  expect(q.prioritizeEstimate(thirdId)).toBe(true);expect(q.state().jobs[2].estimatePriorityOrder).toBe(2);expect(q.cancelPrioritizedEstimate(thirdId)).toBe(true);expect(q.state().jobs[2].estimatePriorityOrder).toBeNull();expect(q.remove(thirdId)).toBe(true);
  await new Promise(resolve=>setTimeout(resolve,100));expect(q.state().jobs[0].status).toBe('processing');
  release();await until(()=>q.state().jobs[1].status==='processing');expect(q.state().jobs[0].status).toBe('completed');expect(q.state().jobs[1].estimateStatus).toBe('estimated');expect(await q.cancel(secondId)).toBe(true);await until(()=>!q.state().running)
},20000)});
const run=(args:string[])=>new Promise<number|null>((resolve,reject)=>{const p=spawn('ffmpeg',args,{shell:false});p.on('error',reject);p.on('close',resolve)});async function until(check:()=>boolean){const end=Date.now()+10000;while(!check()){if(Date.now()>end)throw new Error('Timed out');await new Promise(r=>setTimeout(r,25))}}
