import { useEffect, useMemo, useRef, useState } from 'react';
import { calculateQueueSummary, type AgentEvent, type CompressionJob, type PresetId, type QueueState, type SelectionResponse } from '@video-compressor/shared';
import { agentUrl, connect, consumePairingToken, eventUrl, onPairingToken, request, requestBody } from './api/client';
import { failureState, type ConnectionState, versionState } from './connection';

const empty: QueueState = { jobs: [], running: false, tools: { ffmpeg: false, ffprobe: false }, settings: { preset: 'balanced', outputMode: 'next-to-originals', outputFolder: null }, warning: null };
const downloadUrl = import.meta.env.VITE_AGENT_DOWNLOAD_URL;
const presets: { id: PresetId; title: string; note: string }[] = [{id:'quality',title:'Quality',note:'Original dimensions with the best visual quality.'},{id:'balanced',title:'Balanced',note:'Great everyday size and quality, up to 720p.'},{id:'ultra-small',title:'Ultra Small',note:'Smallest shareable files, up to 550p.'}];

export default function App() {
  const [state, setState] = useState(empty), [connection, setConnection] = useState<ConnectionState>('checking'), [message, setMessage] = useState(''), [help, setHelp] = useState(false);
  const events = useRef<EventSource | null>(null), connectedOnce = useRef(false), connecting = useRef(false);
  const connected = connection === 'connected';

  const establish = async (mode: 'checking' | 'connecting', retry = false) => {
    if (connecting.current) return; connecting.current = true; setConnection(mode); events.current?.close(); events.current = null;
    const deadline = Date.now() + (retry ? 12_000 : 2_500);
    do {
      const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 2200);
      try {
        const result = await connect(controller.signal); clearTimeout(timer);
        const next = versionState(result.apiVersion); setConnection(next);
        if (next !== 'connected') { connecting.current = false; return; }
        setState(result.state); connectedOnce.current = true;
        const source = new EventSource(eventUrl()); events.current = source;
        source.onmessage = e => { const event = JSON.parse(e.data) as AgentEvent; setState(event.state); setConnection('connected'); };
        source.onerror = () => { source.close(); events.current = null; setConnection('disconnected'); };
        connecting.current = false; return;
      } catch { clearTimeout(timer); }
      if (!retry) break;
      await new Promise(resolve => setTimeout(resolve, 900));
    } while (Date.now() < deadline);
    setConnection(connectedOnce.current ? 'disconnected' : await failureState()); connecting.current = false;
  };

  useEffect(() => { consumePairingToken(); void establish('checking'); const remove = onPairingToken(() => void establish('connecting', true)); return () => { remove(); events.current?.close(); }; }, []);
  const action = async (url: string, method = 'POST') => { try { setMessage(''); setState(await request<QueueState>(url, method)); } catch (e) { setMessage(errorText(e)); setConnection('disconnected'); } };
  const setting = async (body: object) => { try { setState(await requestBody<QueueState>('/api/settings', body)); } catch (e) { setMessage(errorText(e)); } };
  const selectFiles = async () => { try { const result=await request<SelectionResponse>('/api/files/select','POST'); setState(result.state); if(result.warnings.length){const text=result.warnings.map(w=>`${w.fileName}: ${w.message}`).join('\n');if(window.confirm(`${text}\n\nAdd anyway?`))setState(await requestBody<QueueState>('/api/files/confirm',{ids:result.warnings.map(w=>w.id)}));} } catch(e){setMessage(errorText(e));} };
  const completed=state.jobs.filter(j=>j.status==='completed').length, overall=useMemo(()=>state.jobs.length?state.jobs.reduce((sum,j)=>sum+(j.status==='completed'?100:j.progress??0),0)/state.jobs.length:0,[state]), summary=useMemo(()=>calculateQueueSummary(state.jobs),[state.jobs]);
  const copyDiagnostics=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(await request('/api/diagnostics'),null,2));setMessage('Safe diagnostics copied.')}catch(e){setMessage(errorText(e))}};

  if (connection === 'checking') return <main><header><Brand/></header><section className="panel connectionCard"><span className="spinner"/><h2>Connecting to the Mac Agent…</h2></section></main>;
  if (!connected && !connectedOnce.current) return <main><header><Brand/><ConnectionBadge state={connection}/></header><Onboarding state={connection} help={help} setHelp={setHelp} connect={()=>void establish('connecting',true)}/></main>;

  return <main><header><Brand/><div className="headerStatus"><ConnectionBadge state={connection}/>{connected&&<button className="link" onClick={copyDiagnostics}>Copy diagnostics</button>}</div></header>
    {!connected&&<section className="disconnectBar"><div><strong>Agent disconnected</strong><span>Open the Mac Agent to restore your current queue.</span></div><button onClick={()=>void establish('connecting',true)}>Reconnect</button></section>}
    <div className={!connected?'disabledArea':''}><section className="panel controls"><div className="controlBlock"><label>Compression</label><div className="segments">{presets.map(p=><button disabled={!connected} className={state.settings.preset===p.id?'selected':''} onClick={()=>setting({preset:p.id})} key={p.id}>{p.title}</button>)}</div><small>{presets.find(p=>p.id===state.settings.preset)?.note}</small></div><div className="controlBlock"><label>Save results</label><div className="segments"><button disabled={!connected} className={state.settings.outputMode==='next-to-originals'?'selected':''} onClick={()=>setting({outputMode:'next-to-originals'})}>Next to originals</button><button disabled={!connected} className={state.settings.outputMode==='chosen-folder'?'selected':''} onClick={()=>action('/api/output/select')}>Choose output folder</button></div><small>{state.settings.outputMode==='chosen-folder'?state.settings.outputFolder??'Choose a folder':'Each result stays beside its source.'}</small></div></section>
    <section className="panel actions"><div><button className="primary" disabled={!connected} onClick={selectFiles}>Select videos</button><button disabled={!connected||!state.jobs.some(j=>j.status==='queued')} onClick={()=>action('/api/queue/start')}>Start compression</button></div><p>🔒 Files stay on this Mac</p></section></div>
    {(!state.tools.ffmpeg||!state.tools.ffprobe)&&connected&&<div className="alert">The bundled video engine is unavailable. Reinstall the Mac Agent.</div>}{state.warning&&<div className="alert">{state.warning}</div>}{message&&<div className="alert">{message}</div>}
    <section className="summary"><div><strong>{completed} / {state.jobs.length}</strong><span>files completed</span></div><div className="overall"><span>Overall progress <b>{Math.round(overall)}%</b></span><progress value={overall} max="100"/></div>{state.jobs.some(j=>['completed','failed','cancelled'].includes(j.status))&&<button disabled={!connected} className="link" onClick={()=>action('/api/jobs/completed','DELETE')}>Clear finished</button>}</section>
    <section className="queue">{state.jobs.length===0?<div className="empty"><h2>Your queue is empty</h2><p>Select one or more videos to begin.</p></div>:state.jobs.map(job=><Job key={job.id} job={job} action={action} disabled={!connected}/>)}</section>
    {state.jobs.length>0&&!state.running&&<section className="panel finalSummary"><div><p>Completed</p><strong>{summary.successful}</strong></div><div><p>Errors</p><strong>{summary.failed}</strong></div><div><p>Original</p><strong>{formatSize(summary.originalSize)}</strong></div><div><p>Result</p><strong>{formatSize(summary.finalSize)}</strong></div><div><p>Space saved</p><strong>{formatSize(summary.savedBytes)} · {summary.savedPercent}%</strong></div>{summary.successful>0&&<button disabled={!connected} onClick={()=>action('/api/output/reveal')}>Show output folder</button>}</section>}
  </main>;
}

function Brand(){return <div><p className="eyebrow">PRIVATE · LOCAL · SIMPLE</p><h1>Local Video Compressor</h1><p className="sub">Smaller videos, without leaving your Mac.</p></div>}
function ConnectionBadge({state}:{state:ConnectionState}){const text=state==='connected'?'Agent connected':state==='connecting'?'Looking for the Mac Agent…':state==='incompatible_version'?'Agent update required':state==='connection_blocked'?'Connection blocked':state==='disconnected'?'Agent disconnected':'Mac Agent is not running';return <span className={`connection ${state==='connected'?'online':''}`}><i/>{text}</span>}
function Onboarding({state,help,setHelp,connect}:{state:ConnectionState;help:boolean;setHelp:(v:boolean)=>void;connect:()=>void}){return <section className="panel onboarding"><div className="onboardingIcon">↓</div>{state==='connecting'?<><span className="spinner"/><h2>Looking for the Mac Agent…</h2><p>Please keep the Agent open. This may take a few seconds.</p></>:state==='incompatible_version'?<><h2>Your Mac Agent needs an update.</h2><p>Install the latest Apple Silicon test version to continue.</p><a className="button primary" href={downloadUrl}>Download latest version</a></>:state==='connection_blocked'?<><h2>Your browser blocked access to the Mac Agent.</h2><p>Allow Local Network access and try again.</p><div className="onboardingActions"><button className="primary" onClick={connect}>Try again</button><a className="button" href={`${agentUrl}/local`} target="_blank">Open local version</a></div></>:<><h2>Compress videos privately on your Mac</h2><p>Install the free Mac Agent to process videos locally.<br/><strong>Your files are never uploaded.</strong></p><p className="platformNote">For Apple Silicon Macs</p><div className="onboardingActions"><a className="button primary" href={downloadUrl}>Download Agent for Mac</a><button onClick={connect}>I’ve opened the Agent — Connect</button></div><button className="helpLink" onClick={()=>setHelp(!help)}>Installation help</button>{help&&<div className="installHelp"><ol><li>Download the Mac Agent.</li><li>Open the downloaded ZIP.</li><li>Move Local Video Compressor Agent to Applications.</li><li>Control-click the app and choose Open.</li><li>Confirm Open.</li><li>Return to this page.</li></ol><p>This warning appears because the test version is not yet notarized by Apple.</p></div>}</>}</section>}
function Job({job,action,disabled}:{job:CompressionJob;action:(url:string,method?:string)=>void;disabled:boolean}){const saving=job.finalSize===null||job.originalSize===0?null:Math.round((1-job.finalSize/job.originalSize)*100);return <article className="job"><div className="jobtop"><div><h3 title={job.fileName}>{job.fileName}</h3><span className={`status ${job.status}`}>{job.status}</span></div><div>{job.status==='processing'&&<button disabled={disabled} className="danger" onClick={()=>action(`/api/jobs/${job.id}/cancel`)}>Cancel</button>}{job.status==='queued'&&<button disabled={disabled} className="link" onClick={()=>action(`/api/jobs/${job.id}`,'DELETE')}>Remove</button>}{['failed','interrupted','cancelled'].includes(job.status)&&<button disabled={disabled} onClick={()=>action(`/api/jobs/${job.id}/retry`)}>Retry</button>}{job.status==='completed'&&<button disabled={disabled} onClick={()=>action(`/api/jobs/${job.id}/reveal`)}>Show in Finder</button>}</div></div><progress value={job.progress??undefined} max="100"/><div className="meta"><span>{formatSize(job.originalSize)} → {job.finalSize===null?'—':formatSize(job.finalSize)}</span><span>{job.progress===null&&job.status==='processing'?'Working…':`${Math.round(job.progress??0)}%`}{saving!==null?` · ${saving}% saved`:''}</span></div>{!['completed','processing'].includes(job.status)&&<Estimate job={job}/>} {job.error&&<p className="error">{job.error}</p>}</article>}
function Estimate({job}:{job:CompressionJob}){const status=job.estimateStatus??'waiting';if(status==='estimating')return <div className="estimateLine"><i className="estimateSpinner"/>Estimating size… {job.estimateProgress?`${job.estimateProgress.completed}/${job.estimateProgress.total}`:''}</div>;if(status==='estimated'&&job.estimatedOutputBytes!=null){const saving=job.estimatedSavingPercent??0;return <div className="estimateLine estimated">◇ Estimated ≈ {formatEstimate(job.estimatedOutputBytes)} · {saving>=0?`≈${saving}% smaller`:'may be larger'}</div>}if(status==='unavailable')return <div className="estimateLine unavailable">Estimate unavailable</div>;if(status==='cancelled')return <div className="estimateLine">Estimate paused</div>;return <div className="estimateLine">Waiting for estimate</div>}
function formatSize(bytes:number){if(!bytes)return'0 B';if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return`${(bytes/1024**2).toFixed(1)} MB`;return`${(bytes/1024**3).toFixed(2)} GB`}
function errorText(value:unknown){return value instanceof Error?value.message:'Something went wrong.'}
function formatEstimate(bytes:number){return `${Math.max(1,Math.round(bytes/1024**2))} MB`}
