import { useEffect, useMemo, useRef, useState } from 'react';
import { calculateQueueSummary, DEFAULT_FRAME_RATE, FRAME_RATE_MAX, FRAME_RATE_MIN, type AgentEvent, type CompressionJob, type PresetId, type QueueState, type SelectionResponse } from '@video-compressor/shared';
import { agentUrl, connect, consumePairingToken, eventUrl, onPairingToken, request, requestBody } from './api/client';
import { failureState, type ConnectionState, versionState } from './connection';
import { type TranslationKey, useI18n } from './i18n';

const empty: QueueState = { jobs: [], running: false, tools: { ffmpeg: false, ffprobe: false }, settings: { preset: 'balanced', outputMode: 'next-to-originals', outputFolder: null }, warning: null };
const downloadUrl = import.meta.env.VITE_AGENT_DOWNLOAD_URL;
const presets: { id: PresetId; title: TranslationKey; note: TranslationKey }[] = [{id:'quality',title:'quality',note:'qualityNote'},{id:'balanced',title:'balanced',note:'balancedNote'},{id:'ultra-small',title:'ultraSmall',note:'ultraSmallNote'}];

export default function App() {
  const { language, setLanguage, t } = useI18n();
  const [state, setState] = useState(empty), [connection, setConnection] = useState<ConnectionState>('checking'), [message, setMessage] = useState(''), [help, setHelp] = useState(false);
  const events = useRef<EventSource | null>(null), connectedOnce = useRef(false), connecting = useRef(false);
  const connected = connection === 'connected';
  const [fps, setFps] = useState<number>(DEFAULT_FRAME_RATE); const fpsTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  const establish = async (mode: 'checking' | 'connecting', retry = false) => {
    if (connecting.current) return; connecting.current = true; setConnection(mode); events.current?.close(); events.current = null;
    const deadline = Date.now() + (retry ? 12_000 : 2_500);
    do {
      const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 2200);
      try {
        const result = await connect(controller.signal); clearTimeout(timer);
        const next = versionState(result.apiVersion); setConnection(next);
        if (next !== 'connected') { connecting.current = false; return; }
        setState(result.state); connectedOnce.current = true;
        const source = new EventSource(eventUrl()); events.current = source;
        source.onmessage = e => { const event = JSON.parse(e.data) as AgentEvent; setState(event.state); setConnection('connected'); };
        source.onerror = () => { source.close(); events.current = null; setConnection('disconnected'); };
        connecting.current = false; return;
      } catch { clearTimeout(timer); }
      if (!retry) break;
      await new Promise(resolve => setTimeout(resolve, 900));
    } while (Date.now() < deadline);
    setConnection(connectedOnce.current ? 'disconnected' : await failureState()); connecting.current = false;
  };

  useEffect(() => { consumePairingToken(); void establish('checking'); const remove = onPairingToken(() => void establish('connecting', true)); return () => { remove(); events.current?.close(); }; }, []);
  const action = async (url: string, method = 'POST') => { try { setMessage(''); setState(await request<QueueState>(url, method)); } catch (e) { setMessage(localizedError(e,t)); setConnection('disconnected'); } };
  const setting = async (body: object) => { try { setState(await requestBody<QueueState>('/api/settings', body)); } catch (e) { setMessage(localizedError(e,t)); } };
  // Slider updates are local and immediate; the agent call (which recomputes the estimate) is
  // debounced so dragging does not flood /api/settings. Server value is only re-synced when idle.
  useEffect(() => { if (!fpsTimer.current) setFps(state.settings.frameRate ?? DEFAULT_FRAME_RATE); }, [state.settings.frameRate]);
  const changeFps = (value: number) => { setFps(value); if (fpsTimer.current) clearTimeout(fpsTimer.current); fpsTimer.current = setTimeout(() => { fpsTimer.current = undefined; void setting({ frameRate: value }); }, 350); };
  const selectFiles = async () => { try { const result=await request<SelectionResponse>('/api/files/select','POST'); setState(result.state); if(result.warnings.length){const text=result.warnings.map(w=>`${w.fileName}: ${t(w.reason==='duplicate'?'duplicate':'alreadyCompressed')}`).join('\n');if(window.confirm(`${text}\n\n${t('addAnyway')}`))setState(await requestBody<QueueState>('/api/files/confirm',{ids:result.warnings.map(w=>w.id)}));} } catch(e){setMessage(localizedError(e,t));} };
  const completed=state.jobs.filter(j=>j.status==='completed').length, overall=useMemo(()=>state.jobs.length?state.jobs.reduce((sum,j)=>sum+(j.status==='completed'?100:j.progress??0),0)/state.jobs.length:0,[state]), summary=useMemo(()=>calculateQueueSummary(state.jobs),[state.jobs]);
  const copyDiagnostics=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(await request('/api/diagnostics'),null,2));setMessage(t('diagnosticsCopied'));}catch(e){setMessage(localizedError(e,t));}};
  const languageSwitch = <LanguageSwitch language={language} setLanguage={setLanguage} t={t}/>;

  if (connection === 'checking') return <main><header><Brand t={t}/><div className="headerStatus">{languageSwitch}</div></header><section className="panel connectionCard"><span className="spinner"/><h2>{t('connectingAgent')}</h2></section></main>;
  if (!connected && !connectedOnce.current) return <main><header><Brand t={t}/><div className="headerStatus">{languageSwitch}<ConnectionBadge state={connection} t={t}/></div></header><Onboarding state={connection} help={help} setHelp={setHelp} connect={()=>void establish('connecting',true)} t={t}/></main>;

  return <main><header><Brand t={t}/><div className="headerStatus">{languageSwitch}<ConnectionBadge state={connection} t={t}/>{connected&&<button className="link" onClick={copyDiagnostics}>{t('copyDiagnostics')}</button>}</div></header>
    {!connected&&<section className="disconnectBar"><div><strong>{t('agentDisconnected')}</strong><span>{t('restoreQueue')}</span></div><button onClick={()=>void establish('connecting',true)}>{t('reconnect')}</button></section>}
    <div className={!connected?'disabledArea':''}><section className="panel controls"><div className="controlBlock"><label>{t('compression')}</label><div className="segments">{presets.map(p=><button disabled={!connected} className={state.settings.preset===p.id?'selected':''} onClick={()=>setting({preset:p.id})} key={p.id}>{t(p.title)}</button>)}</div><small>{t(presets.find(p=>p.id===state.settings.preset)?.note??'balancedNote')}</small></div>{state.settings.preset==='quality'&&<div className="controlBlock"><label>{t('frameRate')} <b>{fps} {t('fpsUnit')}</b></label><input className="fpsSlider" type="range" min={FRAME_RATE_MIN} max={FRAME_RATE_MAX} step={1} value={fps} disabled={!connected} onChange={e=>changeFps(Number(e.target.value))}/><small className="wrap">{t('frameRateNote')}</small></div>}<div className="controlBlock"><label>{t('saveResults')}</label><div className="segments"><button disabled={!connected} className={state.settings.outputMode==='next-to-originals'?'selected':''} onClick={()=>setting({outputMode:'next-to-originals'})}>{t('nextToOriginals')}</button><button disabled={!connected} className={state.settings.outputMode==='chosen-folder'?'selected':''} onClick={()=>action('/api/output/select')}>{t('chooseFolder')}</button></div><small>{state.settings.outputMode==='chosen-folder'?state.settings.outputFolder??t('chooseAFolder'):t('besideSource')}</small></div></section>
    <section className="panel actions"><div><button className="primary" disabled={!connected} onClick={selectFiles}>{t('selectVideos')}</button><button disabled={!connected||!state.jobs.some(j=>j.status==='queued')} onClick={()=>action('/api/queue/start')}>{t('startCompression')}</button></div><p>{t('filesStay')}</p></section></div>
    {(!state.tools.ffmpeg||!state.tools.ffprobe)&&connected&&<div className="alert">{t('engineUnavailable')}</div>}{state.warning&&<div className="alert">{localizedAgentText(state.warning,t)}</div>}{message&&<div className="alert">{message}</div>}
    <section className="summary"><div><strong>{completed} / {state.jobs.length}</strong><span>{t('filesCompleted')}</span></div><div className="overall"><span>{t('overallProgress')} <b>{Math.round(overall)}%</b></span><progress value={overall} max="100"/></div>{state.jobs.some(j=>['completed','failed','cancelled'].includes(j.status))&&<button disabled={!connected} className="link" onClick={()=>action('/api/jobs/completed','DELETE')}>{t('clearFinished')}</button>}</section>
    <section className="queue">{state.jobs.length===0?<div className="empty"><h2>{t('queueEmpty')}</h2><p>{t('queueEmptyBody')}</p></div>:state.jobs.map(job=><Job key={job.id} job={job} action={action} disabled={!connected} t={t}/>)}</section>
    {state.jobs.length>0&&!state.running&&<section className="panel finalSummary"><div><p>{t('completed')}</p><strong>{summary.successful}</strong></div><div><p>{t('errors')}</p><strong>{summary.failed}</strong></div><div><p>{t('original')}</p><strong>{formatSize(summary.originalSize)}</strong></div><div><p>{t('result')}</p><strong>{formatSize(summary.finalSize)}</strong></div><div><p>{t('spaceSaved')}</p><strong>{formatSize(summary.savedBytes)} · {summary.savedPercent}%</strong></div>{summary.successful>0&&<button disabled={!connected} onClick={()=>action('/api/output/reveal')}>{t('showOutput')}</button>}</section>}
  </main>;
}

type T = (key: TranslationKey) => string;
function Brand({t}:{t:T}){return <div><p className="eyebrow">{t('privateLocalSimple')}</p><h1>{t('title')}</h1><p className="sub">{t('subtitle')}</p></div>}
function LanguageSwitch({language,setLanguage,t}:{language:'en'|'uk';setLanguage:(value:'en'|'uk')=>void;t:T}){return <div className="languageSwitch" aria-label={t('language')}><button className={language==='en'?'active':''} onClick={()=>setLanguage('en')}>EN</button><button className={language==='uk'?'active':''} onClick={()=>setLanguage('uk')}>UA</button></div>}
function ConnectionBadge({state,t}:{state:ConnectionState;t:T}){const keys:Record<ConnectionState,TranslationKey>={checking:'connectingAgent',connecting:'lookingForAgent',connected:'agentConnected',not_installed_or_not_running:'agentNotRunning',incompatible_version:'agentUpdateRequired',connection_blocked:'connectionBlocked',disconnected:'agentDisconnected'};return <span className={`connection ${state==='connected'?'online':''}`}><i/>{t(keys[state])}</span>}
function Onboarding({state,help,setHelp,connect,t}:{state:ConnectionState;help:boolean;setHelp:(v:boolean)=>void;connect:()=>void;t:T}){return <section className="panel onboarding"><div className="onboardingIcon">↓</div>{state==='connecting'?<><span className="spinner"/><h2>{t('lookingForAgent')}</h2><p>{t('keepAgentOpen')}</p></>:state==='incompatible_version'?<><h2>{t('updateTitle')}</h2><p>{t('updateBody')}</p><a className="button primary" href={downloadUrl}>{t('downloadLatest')}</a></>:state==='connection_blocked'?<><h2>{t('blockedTitle')}</h2><p>{t('blockedBody')}</p><div className="onboardingActions"><button className="primary" onClick={connect}>{t('tryAgain')}</button><a className="button" href={`${agentUrl}/local`} target="_blank">{t('openLocal')}</a></div></>:<><h2>{t('onboardingTitle')}</h2><p>{t('onboardingBody')}<br/><strong>{t('neverUploaded')}</strong></p><p className="platformNote">{t('appleSilicon')}</p><div className="onboardingActions"><a className="button primary" href={downloadUrl}>{t('downloadAgent')}</a><button onClick={connect}>{t('connectAgent')}</button></div><button className="helpLink" onClick={()=>setHelp(!help)}>{t('installationHelp')}</button>{help&&<div className="installHelp"><h3>{t('installTitle')}</h3><ol>{(['install1','install2','install3','install4','install5','install6','install7','install8','install9'] as TranslationKey[]).map(key=><li key={key}>{t(key)}</li>)}</ol><p>{t('installFallback')}</p><p>{t('notNotarized')}</p></div>}</>}</section>}
function Job({job,action,disabled,t}:{job:CompressionJob;action:(url:string,method?:string)=>void;disabled:boolean;t:T}){const saving=job.finalSize===null||job.originalSize===0?null:Math.round((1-job.finalSize/job.originalSize)*100),statusKey=`status${job.status[0].toUpperCase()}${job.status.slice(1)}` as TranslationKey;return <article className="job"><div className="jobtop"><div><h3 title={job.fileName}>{job.fileName}</h3><span className={`status ${job.status}`}>{t(statusKey)}</span></div><div>{job.status==='processing'&&<button disabled={disabled} className="danger" onClick={()=>action(`/api/jobs/${job.id}/cancel`)}>{t('cancel')}</button>}{job.status==='queued'&&<button disabled={disabled} className="link" onClick={()=>action(`/api/jobs/${job.id}`,'DELETE')}>{t('remove')}</button>}{['failed','interrupted','cancelled'].includes(job.status)&&<button disabled={disabled} onClick={()=>action(`/api/jobs/${job.id}/retry`)}>{t('retry')}</button>}{job.status==='completed'&&<button disabled={disabled} onClick={()=>action(`/api/jobs/${job.id}/reveal`)}>{t('showFinder')}</button>}</div></div><progress value={job.progress??undefined} max="100"/><div className="meta"><span>{formatSize(job.originalSize)} → {job.finalSize===null?'—':formatSize(job.finalSize)}</span><span>{job.progress===null&&job.status==='processing'?t('working'):`${Math.round(job.progress??0)}%`}{saving!==null?` · ${saving}% ${t('saved')}`:''}</span></div>{!['completed','processing'].includes(job.status)&&<Estimate job={job} t={t}/>} {job.error&&<p className="error">{localizedAgentText(job.error,t)}</p>}</article>}
function Estimate({job,t}:{job:CompressionJob;t:T}){const status=job.estimateStatus??'waiting';if(status==='estimating')return <div className="estimateLine"><i className="estimateSpinner"/>{t('estimating')} {job.estimateProgress?`${job.estimateProgress.completed}/${job.estimateProgress.total}`:''}</div>;if(status==='estimated'&&job.estimatedOutputBytes!=null){const saving=job.estimatedSavingPercent??0;return <div className="estimateLine estimated">◇ {t('estimated')} ≈ {formatEstimate(job.estimatedOutputBytes)} · {saving>=0?`≈${saving}% ${t('smaller')}`:t('mayBeLarger')}</div>}if(status==='unavailable')return <div className="estimateLine unavailable">{t('estimateUnavailable')}</div>;if(status==='cancelled')return <div className="estimateLine">{t('estimatePaused')}</div>;return <div className="estimateLine">{t('waitingEstimate')}</div>}
function localizedError(value:unknown,t:T){const raw=value instanceof Error?value.message:'';const map:Record<string,TranslationKey>={PAIRING_REQUIRED:'pairingRequired',CONNECTION_FAILED:'connectionFailed',TIMEOUT:'timeout','Invalid session token.':'invalidToken'};return t(map[raw]??'genericError')}
function localizedAgentText(raw:string,t:T){if(/already in the queue/i.test(raw))return t('duplicate');if(/already compressed/i.test(raw))return t('alreadyCompressed');if(/bundled video engine|FFmpeg is not installed/i.test(raw))return t('engineUnavailable');if(/source file is no longer available/i.test(raw))return t('sourceUnavailable');if(/file could not be processed/i.test(raw))return t('fileProcessFailed');if(/compression was cancelled/i.test(raw))return t('compressionCancelled');if(/FFmpeg could not compress/i.test(raw))return t('compressionFailed');if(/free space may be insufficient/i.test(raw))return t('diskWarning');if(/could not check free space/i.test(raw))return t('diskCheckFailed');return t('genericError')}
function formatSize(bytes:number){if(!bytes)return'0 B';if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return`${(bytes/1024**2).toFixed(1)} MB`;return`${(bytes/1024**3).toFixed(2)} GB`}
function formatEstimate(bytes:number){return `${Math.max(1,Math.round(bytes/1024**2))} MB`}
