import { useEffect, useMemo, useState } from 'react';
import { calculateQueueSummary, type AgentEvent, type CompressionJob, type PresetId, type QueueState, type SelectionResponse } from '@video-compressor/shared';
import { connect, eventUrl, request, requestBody } from './api/client';
const empty: QueueState = { jobs: [], running: false, tools: { ffmpeg: false, ffprobe: false }, settings: { preset: 'balanced', outputMode: 'next-to-originals', outputFolder: null }, warning: null };
const presets: { id: PresetId; title: string; note: string }[] = [{id:'quality',title:'Quality',note:'Original dimensions with the best visual quality.'},{id:'balanced',title:'Balanced',note:'Great everyday size and quality, up to 720p.'},{id:'ultra-small',title:'Ultra Small',note:'Smallest shareable files, up to 550p.'}];
export default function App(){
 const[state,setState]=useState(empty),[connected,setConnected]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let events:EventSource|undefined;connect().then(initial=>{setState(initial);setConnected(true);events=new EventSource(eventUrl());events.onmessage=e=>{const event=JSON.parse(e.data)as AgentEvent;setState(event.state);setConnected(true)};events.onerror=()=>setConnected(false)}).catch(()=>setConnected(false));return()=>events?.close()},[]);
 const action=async(url:string,method='POST')=>{try{setMessage('');setState(await request<QueueState>(url,method))}catch(e){setMessage(errorText(e))}};
 const setting=async(body:object)=>{try{setState(await requestBody<QueueState>('/api/settings',body))}catch(e){setMessage(errorText(e))}};
 const selectFiles=async()=>{try{const result=await request<SelectionResponse>('/api/files/select','POST');setState(result.state);if(result.warnings.length){const text=result.warnings.map(w=>`${w.fileName}: ${w.message}`).join('\n');if(window.confirm(`${text}\n\nAdd anyway?`))setState(await requestBody<QueueState>('/api/files/confirm',{ids:result.warnings.map(w=>w.id)}))}}catch(e){setMessage(errorText(e))}};
 const completed=state.jobs.filter(j=>j.status==='completed').length;
 const overall=useMemo(()=>state.jobs.length?state.jobs.reduce((sum,j)=>sum+(j.status==='completed'?100:j.progress??0),0)/state.jobs.length:0,[state]);
 const summary=useMemo(()=>calculateQueueSummary(state.jobs),[state.jobs]);
 return <main><header><div><p className="eyebrow">PRIVATE · LOCAL · SIMPLE</p><h1>Local Video Compressor</h1><p className="sub">Smaller videos, without leaving your Mac.</p></div><span className={`connection ${connected?'online':''}`}><i/>{connected?'Agent connected':'Agent unavailable'}</span></header>
 <section className="panel controls"><div className="controlBlock"><label>Compression</label><div className="segments">{presets.map(p=><button className={state.settings.preset===p.id?'selected':''} onClick={()=>setting({preset:p.id})} key={p.id}>{p.title}</button>)}</div><small>{presets.find(p=>p.id===state.settings.preset)?.note}</small></div><div className="controlBlock"><label>Save results</label><div className="segments"><button className={state.settings.outputMode==='next-to-originals'?'selected':''} onClick={()=>setting({outputMode:'next-to-originals'})}>Next to originals</button><button className={state.settings.outputMode==='chosen-folder'?'selected':''} onClick={()=>action('/api/output/select')}>Choose output folder</button></div><small title={state.settings.outputFolder??''}>{state.settings.outputMode==='chosen-folder'?state.settings.outputFolder??'Choose a folder':'Each result stays beside its source.'}</small></div></section>
 <section className="panel actions"><div><button className="primary" disabled={!connected} onClick={selectFiles}>Select videos</button><button disabled={!connected||!state.jobs.some(j=>j.status==='queued')} onClick={()=>action('/api/queue/start')}>Start compression</button></div><p>🔒 Files stay on this Mac</p></section>
 {(!state.tools.ffmpeg||!state.tools.ffprobe)&&connected&&<div className="alert">FFmpeg and FFprobe are required. Run <code>brew install ffmpeg</code>, then restart the agent.</div>}{state.warning&&<div className="alert">{state.warning}</div>}{message&&<div className="alert">{message}</div>}
 <section className="summary"><div><strong>{completed} / {state.jobs.length}</strong><span>files completed</span></div><div className="overall"><span>Overall progress <b>{Math.round(overall)}%</b></span><progress value={overall} max="100"/></div>{state.jobs.some(j=>['completed','failed','cancelled'].includes(j.status))&&<button className="link" onClick={()=>action('/api/jobs/completed','DELETE')}>Clear finished</button>}</section>
 <section className="queue">{state.jobs.length===0?<div className="empty"><h2>Your queue is empty</h2><p>Select one or more videos to begin.</p></div>:state.jobs.map(job=><Job key={job.id} job={job} action={action}/>)}</section>
 {state.jobs.length>0&&!state.running&&<section className="panel finalSummary"><div><p>Completed</p><strong>{summary.successful}</strong></div><div><p>Errors</p><strong>{summary.failed}</strong></div><div><p>Original</p><strong>{formatSize(summary.originalSize)}</strong></div><div><p>Result</p><strong>{formatSize(summary.finalSize)}</strong></div><div><p>Space saved</p><strong>{formatSize(summary.savedBytes)} · {summary.savedPercent}%</strong></div>{summary.successful>0&&<button onClick={()=>action('/api/output/reveal')}>Show output folder</button>}</section>}</main>;
}
function Job({job,action}:{job:CompressionJob;action:(url:string,method?:string)=>void}){const saving=job.finalSize===null||job.originalSize===0?null:Math.round((1-job.finalSize/job.originalSize)*100);return <article className="job"><div className="jobtop"><div className="jobIdentity"><h3 title={job.fileName}>{job.fileName}</h3><span className={`status ${job.status}`}>{job.status}</span></div><div className="jobActions">{job.status==='processing'&&<button className="danger" onClick={()=>action(`/api/jobs/${job.id}/cancel`)}>Cancel</button>}{job.status==='queued'&&<button className="link" onClick={()=>action(`/api/jobs/${job.id}`,'DELETE')}>Remove</button>}{['failed','interrupted','cancelled'].includes(job.status)&&<button onClick={()=>action(`/api/jobs/${job.id}/retry`)}>Retry</button>}{job.status==='completed'&&<button onClick={()=>action(`/api/jobs/${job.id}/reveal`)}>Show in Finder</button>}</div></div><progress value={job.progress??undefined} max="100"/><div className="meta"><span>{formatSize(job.originalSize)} → {job.finalSize===null?'—':formatSize(job.finalSize)}</span><span>{job.progress===null&&job.status==='processing'?'Working…':`${Math.round(job.progress??0)}%`}{saving!==null?` · ${saving}% saved`:''}</span></div>{job.status==='queued'&&<Estimate job={job}/>} {job.error&&<p className="error">{job.error}</p>}</article>}
function Estimate({job}:{job:CompressionJob}){const status=job.estimateStatus??'waiting';if(status==='estimating')return <div className="estimateLine"><i className="estimateSpinner"/>Estimating size… {job.estimateProgress?`${job.estimateProgress.completed}/${job.estimateProgress.total}`:''}</div>;if(status==='estimated'&&job.estimatedOutputBytes!=null){const range=job.estimateRangeMinBytes!=null&&job.estimateRangeMaxBytes!=null?`Likely range: ${formatEstimate(job.estimateRangeMinBytes)}–${formatEstimate(job.estimateRangeMaxBytes)}. `:'';const saving=job.estimatedSavingPercent??0;return <div className="estimateLine estimated" title={`Estimate only. Actual size may differ. ${range}Actual size depends on video complexity.`}>◇ Estimated ≈ {formatEstimate(job.estimatedOutputBytes)} · {saving>=0?`≈${saving}% smaller`:'may be larger'}</div>}if(status==='unavailable')return <div className="estimateLine unavailable" title={job.estimateError??'Estimate unavailable'}>Estimate unavailable</div>;if(status==='cancelled')return <div className="estimateLine">Estimate paused</div>;return <div className="estimateLine">Waiting for estimate</div>}
function formatSize(bytes:number){if(!bytes)return'0 B';if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return`${(bytes/1024**2).toFixed(1)} MB`;return`${(bytes/1024**3).toFixed(2)} GB`}
function errorText(value:unknown){return value instanceof Error?value.message:'Something went wrong.'}
function formatEstimate(bytes:number){return `${Math.max(1,Math.round(bytes/1024**2))} MB`}
