import { PGlite } from '@electric-sql/pglite';
import { setQueryExecutor } from '../../scripts/analytics/db';

/**
 * An in-process Postgres with the three analytics objects the CLI reads
 * (`analytics_events` with the v2 envelope columns, `analytics_users`,
 * `analytics_team_workspace`) plus the 028 sync-jobs view as a plain table, so
 * `audit` can count it. The CLI's exact SQL runs against it through the
 * pluggable executor; nothing here is shared with production.
 */
export interface AnalyticsTestDb {
  db: PGlite;
  exec(sql: string): Promise<void>;
  close(): Promise<void>;
}

export const ANALYTICS_SCHEMA = `
  create table public.analytics_users (
    id uuid primary key,
    email text,
    email_normalized text,
    display_name text,
    language text,
    plan text,
    account_status text,
    marketing_consent boolean,
    registered_at timestamptz,
    last_seen_at timestamptz,
    last_login_at timestamptz
  );
  create table public.analytics_events (
    id bigint generated by default as identity primary key,
    user_id uuid,
    event_name text not null,
    session_id uuid,
    tool text,
    properties jsonb not null default '{}'::jsonb,
    app_version text,
    agent_version text,
    locale text,
    platform text,
    occurred_at timestamptz not null default now(),
    flow_id uuid,
    event_id uuid,
    session_sequence integer,
    installation_id uuid,
    run_id uuid,
    local_app_version text,
    local_app_build text,
    web_build_id text,
    architecture text,
    feature text,
    error_code text,
    error_stage text,
    error_fingerprint text,
    outcome text,
    -- envelope v3 (migration 20261117110000).
    attempt_id text,
    agent_instance_id uuid,
    agent_platform text,
    created_at timestamptz not null default now()
  );
  create table public.analytics_team_workspace (
    workspace_key text not null,
    member_user_id uuid not null,
    member_joined_at timestamptz not null,
    member_removed_at timestamptz,
    root_connected_at timestamptz not null,
    root_state text not null,
    pilot_enrolled_at timestamptz not null,
    pilot_exited_at timestamptz
  );
  create table public.analytics_catalog_sync_jobs (
    job_id uuid primary key default gen_random_uuid(),
    team_id uuid,
    connection_id uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
  );
`;

export async function createAnalyticsDb(): Promise<AnalyticsTestDb> {
  const db = await PGlite.create();
  await db.exec(ANALYTICS_SCHEMA);

  // PGlite has a single connection and does not tolerate overlapping queries;
  // a real pg Pool (max 3) does. Serialize so Promise.all call sites in the CLI
  // behave here exactly as they do in production.
  let chain: Promise<unknown> = Promise.resolve();
  setQueryExecutor((sql, params) => {
    const run = chain.then(async () => {
      const result = await db.query(sql, params as unknown[]);
      // Mirror production's bigint/numeric -> number coercion (see db.ts type parsers).
      return (result.rows as Record<string, unknown>[]).map(row => {
        const out: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(row)) {
          out[key] =
            typeof value === 'string' && /^-?\d+(\.\d+)?$/.test(value) ? Number(value) : value;
        }
        return out;
      });
    });
    chain = run.catch(() => undefined);
    return run;
  });

  return {
    db,
    exec: sql => db.exec(sql).then(() => undefined),
    close: async () => {
      setQueryExecutor(null);
      await db.close();
    }
  };
}
