-- First-party, privacy-minimized product analytics. No media, filenames or paths.

create or replace function public.analytics_properties_are_safe(payload jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    jsonb_typeof(payload) = 'object'
    and octet_length(payload::text) <= 2048
    and not exists (
      select 1
      from jsonb_object_keys(payload) as property_key
      where property_key <> all (array[
        'video_count',
        'total_input_bytes',
        'total_output_bytes',
        'saving_percent',
        'processing_duration_ms',
        'mode',
        'crf',
        'rate_control',
        'output_fps',
        'target_resolution',
        'image_embedding',
        'success',
        'error_category',
        'tool_identifier',
        'language',
        'marketing_consent'
      ])
    )
    and case when payload ? 'video_count' then
      jsonb_typeof(payload -> 'video_count') = 'number'
      and (payload ->> 'video_count')::numeric between 0 and 10000
      else true end
    and case when payload ? 'total_input_bytes' then
      jsonb_typeof(payload -> 'total_input_bytes') = 'number'
      and (payload ->> 'total_input_bytes')::numeric between 0 and 9007199254740991
      else true end
    and case when payload ? 'total_output_bytes' then
      jsonb_typeof(payload -> 'total_output_bytes') = 'number'
      and (payload ->> 'total_output_bytes')::numeric between 0 and 9007199254740991
      else true end
    and case when payload ? 'saving_percent' then
      jsonb_typeof(payload -> 'saving_percent') = 'number'
      and (payload ->> 'saving_percent')::numeric between -10000 and 100
      else true end
    and case when payload ? 'processing_duration_ms' then
      jsonb_typeof(payload -> 'processing_duration_ms') = 'number'
      and (payload ->> 'processing_duration_ms')::numeric between 0 and 31536000000
      else true end
    and case when payload ? 'crf' then
      jsonb_typeof(payload -> 'crf') = 'number'
      and (payload ->> 'crf')::numeric between 0 and 63
      else true end
    and case when payload ? 'output_fps' then
      jsonb_typeof(payload -> 'output_fps') = 'number'
      and (payload ->> 'output_fps')::numeric between 1 and 1000
      else true end
    and case when payload ? 'target_resolution' then
      jsonb_typeof(payload -> 'target_resolution') = 'number'
      and (payload ->> 'target_resolution')::numeric between 16 and 32768
      else true end
    and case when payload ? 'image_embedding' then
      jsonb_typeof(payload -> 'image_embedding') = 'boolean'
      else true end
    and case when payload ? 'success' then
      jsonb_typeof(payload -> 'success') = 'boolean'
      else true end
    and case when payload ? 'marketing_consent' then
      jsonb_typeof(payload -> 'marketing_consent') = 'boolean'
      else true end
    and case when payload ? 'mode' then
      payload ->> 'mode' in ('optimal', 'custom')
      else true end
    and case when payload ? 'rate_control' then
      payload ->> 'rate_control' in ('crf', 'bitrate')
      else true end
    and case when payload ? 'language' then
      payload ->> 'language' in ('en', 'uk')
      else true end
    and case when payload ? 'tool_identifier' then
      payload ->> 'tool_identifier' in ('compressor', 'transcription')
      else true end
    and case when payload ? 'error_category' then
      payload ->> 'error_category' in (
        'agent_unavailable',
        'agent_disconnected',
        'unsupported_media',
        'source_unavailable',
        'insufficient_space',
        'output_validation',
        'image_processing',
        'cancelled',
        'network',
        'unknown'
      )
      else true end;
$$;

create table public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  session_id uuid,
  tool text,
  properties jsonb not null default '{}'::jsonb,
  app_version text,
  agent_version text,
  locale text,
  platform text,
  created_at timestamptz not null default now(),
  constraint analytics_event_name_check check (event_name in (
    'user_signed_in',
    'user_signed_out',
    'home_viewed',
    'tool_opened',
    'agent_connected',
    'agent_disconnected',
    'agent_update_required',
    'videos_added',
    'estimate_started',
    'estimate_completed',
    'compression_batch_started',
    'compression_started',
    'compression_completed',
    'compression_failed',
    'image_embedding_enabled',
    'transcription_interest_clicked',
    'language_changed',
    'marketing_consent_changed'
  )),
  constraint analytics_properties_check check (public.analytics_properties_are_safe(properties)),
  constraint analytics_tool_check check (tool is null or tool in ('compressor', 'transcription')),
  constraint analytics_locale_check check (locale is null or locale in ('en', 'uk')),
  constraint analytics_platform_check check (
    platform is null or platform in ('macos', 'windows', 'linux', 'other')
  ),
  constraint analytics_text_lengths_check check (
    (app_version is null or char_length(app_version) <= 64)
    and (agent_version is null or char_length(agent_version) <= 64)
  )
);

create index analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index analytics_events_user_id_idx on public.analytics_events (user_id);
create index analytics_events_event_name_idx on public.analytics_events (event_name);
create index analytics_events_tool_idx on public.analytics_events (tool);
create index analytics_events_event_created_idx
  on public.analytics_events (event_name, created_at desc);
create index analytics_events_tool_created_idx
  on public.analytics_events (tool, created_at desc)
  where tool is not null;
create index analytics_events_user_created_idx
  on public.analytics_events (user_id, created_at desc)
  where user_id is not null;

alter table public.analytics_events enable row level security;

create policy analytics_insert_own
on public.analytics_events
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and user_id = (select auth.uid())
  and public.analytics_properties_are_safe(properties)
);

create policy analytics_admin_select
on public.analytics_events
for select
to authenticated
using (public.is_admin());

-- There are deliberately no UPDATE or DELETE client policies.
revoke all on table public.analytics_events from anon, authenticated;
grant insert (
  user_id,
  event_name,
  session_id,
  tool,
  properties,
  app_version,
  agent_version,
  locale,
  platform
) on table public.analytics_events to authenticated;
grant select on table public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to authenticated;

revoke all on function public.analytics_properties_are_safe(jsonb) from public, anon;
grant execute on function public.analytics_properties_are_safe(jsonb) to authenticated;

comment on table public.analytics_events is 'Allowlisted first-party product events; media identifiers and arbitrary JSON are rejected.';
